epoch: 0                          # epoch to start training from
n_epochs: 1000                    # number of epochs of training
dataset_name: "picmus"
batch_size: 4
lr: 0.0001
b1: 0.5                           # adam: decay of first order momentum of gradient
b2: 0.999                         # adam: decay of first order momentum of gradient
n_cpu: 8                          # number of cpu threads to use during batch generation
img_size: 256                   # size of each image dimension
channels: 1                       # number of image channels
sample_interval: 10               # interval between image sampling
checkpoint_interval: 10
gpu: 1                            # gpu number